// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agkmbgxtmvhsyftcrplp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFna21iZ3h0bXZoc3lmdGNycGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMTYyOTUsImV4cCI6MjA4NjY5MjI5NX0.PVo0dGIWaYP3SGG4SPTzPGVPrAgUqi4u4LkW_pONzrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});